# new branch tests -12
- hosts: all
  become: yes
  tasks:
  - name: print facts
    debug:
      msg:
        - 'inventory: {{ inventory_hostname }}'
        - 'nodename: {{ ansible_nodename }} FQDN: {{ ansible_fqdn }} hostname: {{ ansible_hostname }}'
        - '{{ cluster_name }} in {{ datacenter_name }}'

  # - name: add ESXi Host to vSphere 
  #   community.vmware.vmware_host:
  #     hostname: "{{ vcenter_fqdn }}"
  #     username: "administrator@{{ vcsa_sso_domain }}"
  #     password: "{{ vcenter_password }}"
  #     validate_certs: False
  #     datacenter_name: "{{ datacenter_name }}"
  #     cluster_name:    "{{ cluster_name }}"
  #     esxi_hostname: "{{ ansible_fqdn }}"
  #     esxi_username: "root"
  #     esxi_password: "{{ esxi_password }}"
  #     state: present
  #   delegate_to: localhost

  - name: Enter Maintenance Mode
    community.vmware.vmware_maintenancemode:
      hostname: "{{ vcenter_fqdn }}"
      username: "administrator@{{ vcsa_sso_domain }}"
      password: "{{ vcenter_password }}"
      validate_certs: False
      esxi_hostname: "{{ ansible_fqdn }}"
      evacuate: true
      timeout: 3600
      state: present
    delegate_to: localhost
