- hosts: localhost
  name: Configure VMWare vCenter Slave
  vars_files:
    - env/nested_vcsa_slave.yml
  vars:
    iscsi : "false"
  become: true
  tasks:
    - name: Make sure requirements are met to run vmware_guest_snapshot module
      become: true
      pip:
        name: PyVmomi
        state: present
  roles:
    - role: vcsa_configure
    
    