- name: Gather info from standalone ESXi server having datacenter as 'ha-datacenter'
  community.vmware.vmware_datastore_info:
    hostname: "{{ vcsa_fqdn }}"
    username: "administrator@{{ vcsa_sso_domain }}"
    password: "{{ vcsa_password }}"
    validate_certs: False
    datacenter_name: "PD00"
  delegate_to: localhost
  register: ds_info

# - name: print ds list 
#   debug:
#     msg: "{{ ds_info | to_json | from_json | json_query(ds_name_query) }}"
#   vars:
#     ds_name_query: "datastores[?contains(name,'mclu01')].name"

- name: define vars
  set_fact:
   ds_list: "{{ ds_info | json_query('datastores[*].name') }}"

# - name: print ds 
#   debug:
#     msg: "{{ ds_list[0] }}"

- name: Create Local Content Library
  community.vmware.vmware_content_library_manager:
    hostname: "{{ vcsa_fqdn }}"
    username: "administrator@{{ vcsa_sso_domain }}"
    password: "{{ vcsa_password }}"
    validate_certs: False
    library_name: PD00-content-lib
    library_description: 'Library with Datastore Backing'
    library_type: local
    datastore_name: "{{ ds_list[0] }}"
    state: present
  delegate_to: localhost


