---
-  name: Add Management vmkernel port using static network type
   community.vmware.vmware_vmkernel:
      hostname: "{{ item.0.name }}"
      username: "{{ item.0.user }}"
      password: "{{ item.0.password }}"
      validate_certs: False
      esxi_hostname: "{{ item.0.name }}"
      vswitch_name: "vSwitch0"
      portgroup_name: "Management Network"
      network:
        type: "static"
        ip_address: "{{ item.1.ipv4 }}"
        subnet_mask: "{{ item.1.netmask }}"
        # tcpip_stack: "vmotion"
      state: present
   loop: "{{ esxi_hosts | subelements('esxi_vmks', 'skip_missing=True') }}"
   delegate_to: localhost


# -  name: Add vmkernel port
#    community.vmware.vmware_vmkernel:
#       hostname: "{{ item.0.name }}"
#       username: "{{ item.0.user }}"
#       password: "{{ item.0.password }}"
#       validate_certs: False
#       esxi_hostname: '{{ item.0.name }}'
#       vswitch_name: "{{ item.1.vmswitch }}"
#       portgroup_name: "{{ item.1.name }}"
#       network:
#         type: 'static'
#         ip_address: "{{ item.1.ipv4 }}"
#         subnet_mask: "{{ item.1.netmask }}"
#       state: present
#    loop: "{{ esxi_hosts | subelements('esxi_vmks', 'skip_missing=True') }}"
#    delegate_to: localhost