---
- name: Rebooting VMs
  ansible.windows.win_reboot:
  
- name: Wait default 300 seconds for port 5985 to become open, don't start checking for 15 seconds
  win_wait_for:
    port: 5985
    delay: 15

- name: Setting host facts using key=value pairs, this format can only create strings or booleans
  set_fact: dns1={{ hostvars[groups['ad_primary'][0]].ansible_host }} dns2={{ hostvars[groups['ad_secondary'][0]].ansible_host}}

- name: change DNS server
  win_dns_client:
    adapter_names: '*'
    ipv4_addresses: 
      - '{{ dns1 }}'
      - '{{ dns2 }}' 

- name: install primary ad
  ansible.windows.win_domain:
    domain_admin_user: "Administrator"
    domain_admin_password: "{{ ansible_password }}"
    dns_domain_name: "{{ domain }}"
    safe_mode_password: "{{ domain_safemode_password }}"
  register: ad
  when: "'ad_primary' in group_names"

- name: reboot server
  win_reboot:
    msg: "Installing AD. Rebooting..."
    pre_reboot_delay: 15
    reboot_timeout: 600
    post_reboot_delay: 420
  when: ad.changed

- block:
  - name: change DNS server
    win_dns_client:
      adapter_names: '*'
      ipv4_addresses: 
        - '{{ dns1 }}'
        - '{{ dns2 }}'

  - name: join domain
    win_domain_membership:
      dns_domain_name: "{{ domain }}"
      domain_admin_user: "{{ domain_admin }}"
      domain_admin_password: "{{ ansible_password }}"
      state: domain
    register: domain_joined

  - name: reboot after domain join
    win_reboot:
    when: domain_joined.reboot_required

  - name: Wait for system to become reachable over WinRM
    wait_for_connection:
      timeout: 900

  - name: install ad
    ansible.windows.win_domain_controller:
      dns_domain_name: "{{ domain }}"
      domain_admin_user: "{{ domain_admin }}"
      domain_admin_password: "{{ ansible_password }}"
      safe_mode_password: "{{ domain_safemode_password }}"
      state: domain_controller
    register: ad

  - name: reboot server
    win_reboot:
      msg: "Installing AD. Rebooting..."
      pre_reboot_delay: 15
    when: ad.changed
  when: "'ad_secondary' in group_names"